# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d51a3cf8f278e19e47eea8daed4af9eb57b34adae734ee4134b7174f8be21d9fadffcc64ea3f388f19a2d8d4fa789ac9ece9c7f9ad64dcefc5158946d186eb9

test:
  secret_key_base: c3809a961d52d3c2213ccd79e70253dfef32d6c3eb0cffe5d81ce102b1b219385ea8f738e7b424b293f36f74db2f556017979a69f8c049f0737937ec6f320f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
